# Generated by Django 3.1.3 on 2020-11-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0002_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='ready_status',
        ),
    ]
