# Generated by Django 3.1.3 on 2020-11-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0004_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='type',
            new_name='column_type',
        ),
    ]
