# Generated by Django 3.1.3 on 2020-11-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0005_auto_20201108_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (' ', 'Tab (_)')], default=',', max_length=5),
        ),
    ]
